before_script:
  - apt-get update -y
  - apt-get install -y --no-install-recommends apt-transport-https ca-certificates lsb-release libdistro-info-perl devscripts dh-make dh-exec build-essential libyaml-cpp-dev libboost-filesystem-dev libboost-program-options-dev libboost-date-time-dev
  - echo "deb http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list
  - apt-get update -y
  - apt-get -t stretch-backports install -y --no-install-recommends cmake
  - 'curl -fL https://getcli.jfrog.io | sh'
  - ./jfrog bt c --user "${JFROG_USER}" --key "${JFROG_KEY}" --licenses "${JFROG_LICENSES}"
  - lsb_release -a

stages:
  - test
  - deploy

test:
  stage: test
  environment: test
  only:
    - develop
  script:
    - 'echo "CI_PROJECT_ID: ${CI_PROJECT_ID}"'
    - 'echo "CI_PROJECT_NAME: ${CI_PROJECT_NAME}"'

deploy:
  stage: deploy
  environment: bintray
  only:
    - tags
  script:
    - 'echo "CI_PROJECT_ID: ${CI_PROJECT_ID}"'
    - 'echo "CI_PROJECT_NAME: ${CI_PROJECT_NAME}"'
    - ./jfrog bt vc ${BINTRAY_REPOSITORY}/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}
    - dpkg-buildpackage -b
    - ./jfrog bt u --publish=true --deb=stretch/main/amd64 ../${CI_PROJECT_NAME}_*_amd64.deb ${BINTRAY_REPOSITORY}/${CI_PROJECT_NAME}/${CI_COMMIT_TAG} ${POOL_PREFIX}/${CI_PROJECT_NAME}/
