before_script:
  - apt-get update -y
  - apt-get install -y --no-install-recommends apt-transport-https ca-certificates lsb-release libdistro-info-perl devscripts dh-make dh-exec build-essential libyaml-cpp-dev libboost-filesystem-dev libboost-program-options-dev libboost-date-time-dev
  - lsb_release -a
  - echo "deb http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list
  - apt-get update -y
  - apt-get -t stretch-backports install -y --no-install-recommends cmake
  - cmake --version
  - 'curl -fL https://getcli.jfrog.io | sh'
  - ./jfrog --version
  - ./jfrog bt c --user "${JFROG_USER}" --key "${JFROG_KEY}" --licenses "${JFROG_LICENSES}"

stages:
  - deploy

deploy:
  stage: deploy
  environment: bintray
  only:
    - tags
  script:
    - ./jfrog bt vc ${BINTRAY_REPOSITORY}/${PACKAGE_NAME}/${CI_COMMIT_TAG}
    - dpkg-buildpackage -b
    - ./jfrog bt u --publish=true --deb=stretch/main/amd64 ../${PACKAGE_NAME}_*_amd64.deb ${BINTRAY_REPOSITORY}/${PACKAGE_NAME}/${CI_COMMIT_TAG} ${POOL_PREFIX}/${PACKAGE_NAME}/
